### PR TITLE
Add support for iOS 7.1

### PR DESCRIPTION
**Pull request by stepanhruda**
iPhoneSimulatorRemoteClient got renamed to DVTiPhoneSimulatorRemoteClient.framework and introduced some changes. This PR addresses them.

The project was also converted to ARC from garbage collection and made compilable under Xcode 5.1. I haven't bumped the deployment target all the way to OS X 10.9, because more issues come with it, like strong-to-strong NSMapTable being deprecated (and NSTask not conforming to NSCopying).

The fix is heavily based on how [ios-sim](https://github.com/phonegap/ios-sim) uses the private framework to run the simulator: https://github.com/phonegap/ios-sim/blob/1.9.0/Source/iPhoneSimulator.m

### CODE REVIEW

**Comment by landonf** [comment]
This covers a lot of ground in a single commit, which makes it a bit harder to understand the changes.

Some feedback:
- Breaking this up into a non-squashed single commit would make review (and future understanding of) the changes a lot easier.
- Can you exclude  the white space / style changes to otherwise unmodified code? 
- There's already code in the PLSimulator classes that handles @rpath-aware loading of a bundle and all of the frameworks it depends on -- does this not work anymore, necessitating loadSimulatorFrameworkFromDeveloperDirectory?
- PLSimulatorDiscovery implements XCode framework discovery; the developerDirectoryFromXcodeSelect et al code appears to duplicate/replace this code.
- A failed class lookup inside the PLSimulator code shouldn't trigger a full exit of the process -- loadClientFramework vends an outError parameter for this type of error reporting.

**Comment by stepanhruda** [comment]
You're right, this was more of a quick fix. Re-pushed with proper history and no unnecessary changes.

**Comment by stepanhruda** [comment]
I also addressed the other feedback. The extra needed frameworks are now loaded as part of `PLSimulatorPlatform` using its paths. We're also spitting out an `outError`.

**Comment by landonf** [comment]
Thanks -- one last thing I'm looking at, do you happen to know the purpose of the CFPreferences*() code in deviceInfoNameForFamily:retina:isTallDevice?

**Comment by stepanhruda** [comment]
Since it saves the device family and type to the simulator's preferences, I assume it causes the simulator to load the same device the next time you open it without specifying a device (e.g. from the Xcode menu bar option). `ios-sim` does this since https://github.com/phonegap/ios-sim/commit/9b0ef32dd843d0078ae9075db2b3b216e499b809

**Comment by stepanhruda** [comment]
Anything blocking this? I'm happy to rework stuff you're concerned about.

**Comment by landonf** [comment]
Hey, thanks for checking in. I've got this nearly ready for merge, the last issue was investigating the CFPreferences*() code; it appears to be a no-op for our use case, I just wanted to confirm by stepping through the simulator framework code and haven't had a chance yet.

**Comment by landonf** [comment]
Thanks for the patch!

I've merged this into master, along with some additional changes to support SimulatorHost.framework and integrate with our existing dyld @rpath bundle loading.

If you're interested, one area that's still unexplored is using the new ISHDeviceVersions to allow more fine-grained device selection (see TODO in -[LauncherSimClient launch]).

**Pull request merged**
